## KNN ALGORITHM

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
x=iris.data
y=iris.target



In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(x,y, test_size=0.20)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)


array([[ 2.24987453, -0.20925419,  1.33915128,  1.48168015],
       [ 0.54265266, -0.91992878,  0.66394896,  0.8221786 ],
       [ 0.17681941, -0.91992878,  0.77648268,  0.55837798],
       [-1.1645692 , -0.20925419, -1.30539117, -1.28822637],
       [-1.1645692 ,  1.212095  , -1.30539117, -1.42012668],
       [ 0.54265266, -0.44614572,  1.05781698,  0.8221786 ],
       [-0.31095827, -0.44614572, -0.06752023,  0.16267705],
       [-1.77429129,  0.26452888, -1.36165803, -1.28822637],
       [-0.79873594, -0.91992878,  0.10128035,  0.29457736],
       [ 0.29876383, -0.44614572,  0.55141523,  0.29457736],
       [-1.28651362,  0.73831194, -1.02405686, -1.28822637],
       [ 1.3962636 ,  0.26452888,  0.55141523,  0.29457736],
       [-0.55484711, -0.20925419,  0.43888151,  0.42647767],
       [ 0.7865415 , -0.20925419,  0.83274954,  1.08597922],
       [-0.31095827, -0.20925419,  0.21381407,  0.16267705],
       [-1.04262478, -1.8674949 , -0.23632081, -0.23302388],
       [ 0.17681941, -0.

In [8]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)



KNeighborsClassifier()

In [9]:
y_pred=classifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))    
print(confusion_matrix(y_test,y_pred))
      

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.92      1.00      0.96        11
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]
